AWSTemplateFormatVersion: "2010-09-09"

Description: This stack deploys a basic HTTP static website

Parameters:
  BucketName:
    Description: "Name of the bucket to be created"
    Type: String
    Default: static-s3-bucket-2021-12-17
  DomainName:
    Description: "DNS Domain of the website"
    Type: String
    Default: lab.donato.cloudns.ph
  CertificateARN:
    Description: "the ARN of the certificate"
    Type: String
    Default: "arn:aws:acm:us-east-1:440111066673:certificate/1b375a7c-d312-4b59-a846-4ef13a8fd32d"

Resources:
  S3Bucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName:
        Ref: BucketName
      WebsiteConfiguration:
        IndexDocument: "index.html"
        ErrorDocument: "error.html"

  CloudFrontOriginAccessIdentity:
    Type: "AWS::CloudFront::CloudFrontOriginAccessIdentity"
    Properties:
      CloudFrontOriginAccessIdentityConfig:
        Comment:
          Fn::Sub: "Cloudfront Origin identity for ${DomainName}"

  S3BucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket:
        Ref: BucketName
      PolicyDocument:
        Id: MyPolicy
        Version: 2012-10-17
        Statement:
          - Sid: PublicReadForGetBucketObjects
            Effect: Allow
            #Principal: "*"
            Principal:
              AWS:
                Fn::Sub: "arn:aws:iam::cloudfront:user/CloudFront Origin Access Identity ${CloudFrontOriginAccessIdentity}"
            Action: s3:GetObject
            Resource:
              Fn::Sub: "arn:aws:s3:::${BucketName}/*"

  CloudFrontDistribution:
    Type: "AWS::CloudFront::Distribution"
    Properties:
      DistributionConfig:
        Aliases:
          - Ref: DomainName
        DefaultCacheBehavior:
          AllowedMethods:
            - GET
            - HEAD
            - OPTIONS
          CachedMethods:
            - GET
            - HEAD
            - OPTIONS
          Compress: true
          DefaultTTL: 3600 # in seconds
          ForwardedValues:
            Cookies:
              Forward: none
            QueryString: false
          MaxTTL: 86400 # in seconds
          MinTTL: 60 # in seconds
          TargetOriginId: s3origin
          #ViewerProtocolPolicy: "allow-all"
          ViewerProtocolPolicy: redirect-to-https
        # This DefaultRootObject configuration is not enough.
        DefaultRootObject: index.html
        Enabled: true
        HttpVersion: http2
        Origins:
          - DomainName:
              Fn::GetAtt: [S3Bucket, DomainName]
            Id: s3origin
            S3OriginConfig:
              OriginAccessIdentity:
                Fn::Sub: "origin-access-identity/cloudfront/${CloudFrontOriginAccessIdentity}"
        PriceClass: "PriceClass_All"
        ViewerCertificate:
          AcmCertificateArn:
            Ref: CertificateARN
          MinimumProtocolVersion: TLSv1.2_2021
          SslSupportMethod: sni-only

  DNS:
    Type: AWS::Route53::RecordSetGroup
    Properties:
      HostedZoneName:
        Fn::Sub: ${DomainName}.
      RecordSets:
        - AliasTarget:
            DNSName:
              Fn::GetAtt: [CloudFrontDistribution, DomainName]
            HostedZoneId: Z2FDTNDATAQYW2
          Name:
            Ref: DomainName
          Type: A
